export const data = [
  {
    id: 36,
    name: "Coca Cola",
    image: "./images/Cola-.png",
    price: 1.99,
    calories: 150,
    description: "Chilled soft drink served with ice.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 13,
    name: "BBQ Bacon Burger",
    image: "./images/BBQ Bacon Burger.jpg",
    price: 9.99,
    description: "Grilled beef, crispy bacon, smoky BBQ sauce, and cheese.",
    category: "Burger",
    calories: 650,
    quantity: 1,
  },
  {
    id: 27,
    name: "Cheesecake",
    image: "./images/BlueberryCheesecake.webp",
    price: 6.5,
    calories: 500,
    description: "Creamy cheesecake with a buttery biscuit base.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 3,
    name: "BBQ Chicken Pizza",
    image: "./images/BBQ-Chicken-Pizza-4.jpg",
    price: 11.25,
    description:
      "Grilled chicken with smoky BBQ sauce, onions, and mozzarella cheese.",
    category: "Pizza",
    calories: 500,
    quantity: 1,
  },
  {
    id: 22,
    name: "Pesto Pasta",
    image: "./images/Pesto Pasta.jpeg",
    price: 9.5,
    calories: 550,
    description: "Fresh basil pesto sauce with parmesan cheese.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 40,
    name: "Hot Chocolate",
    image: "./images/hot-chocolate.jpg",
    price: 3.5,
    calories: 210,
    description: "Warm chocolate drink topped with cream.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 17,
    name: "Fettuccine Alfredo",
    image: "./images/fettuccine-alfredo.jpg",
    price: 10.49,
    calories: 750,
    description: "Creamy white sauce pasta with parmesan and butter.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 32,
    name: "Panna Cotta",
    image: "./images/Panna Cotta.webp",
    price: 5.99,
    calories: 300,
    description: "Creamy Italian dessert topped with berries.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 15,
    name: "Chicken Burger",
    image: "./images/Chicken Burger.jpeg",
    price: 7.25,
    description: "Crispy fried chicken breast with mayo and lettuce.",
    category: "Burger",
    calories: 480,
    quantity: 1,
  },
  {
    id: 5,
    name: "Four Cheese Pizza",
    image: "./images/four-cheeses-pizza.avif",
    price: 12.0,
    description:
      "Delicious blend of mozzarella, cheddar, parmesan, and gorgonzola cheese.",
    category: "Pizza",
    calories: 600,
    quantity: 1,
  },
  {
    id: 44,
    name: "Espresso",
    image: "./images/Espresso.jpeg",
    price: 2.5,
    calories: 15,
    description: "Strong and rich Italian coffee shot.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 26,
    name: "Chocolate Cake",
    image: "./images/chocolate-cake-3.jpg",
    price: 5.99,
    calories: 450,
    description: "Rich and moist chocolate layered cake.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 19,
    name: "Lasagna",
    image: "./images/Lasagna.jpg",
    price: 11.25,
    calories: 800,
    description: "Layers of pasta with beef, cheese, and tomato sauce.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 1,
    name: "Margherita Pizza",
    image: "./images/Margherita Pizza.webp",
    price: 8.99,
    description:
      "Classic pizza topped with tomato sauce, mozzarella cheese, and fresh basil.",
    category: "Pizza",
    calories: 300,
    quantity: 1,
  },
  {
    id: 43,
    name: "Green Tea",
    image: "./images/Green Tea.jpeg",
    price: 2.2,
    calories: 20,
    description: "Healthy antioxidant-rich green tea.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 11,
    name: "Classic Beef Burger",
    image: "./images/Classic Beef Burger.webp",
    price: 7.99,
    description: "Juicy beef patty with lettuce, tomato, onions, and cheese.",
    category: "Burger",
    calories: 520,
    quantity: 1,
  },
  {
    id: 35,
    name: "Cupcakes",
    image: "./images/Vanilla-Cupcakes.jpg",
    price: 3.5,
    calories: 280,
    description: "Mini cakes topped with colorful frosting.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 18,
    name: "Penne Arrabbiata",
    image: "./images/Chicken_Penne_Arrabbiata_1.jpg",
    price: 8.99,
    calories: 500,
    description: "Spicy tomato-based pasta with chili and garlic.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 30,
    name: "Brownie",
    image: "././images/Brownie.jpeg",
    price: 4.5,
    calories: 400,
    description: "Fudgy chocolate brownie topped with nuts.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 2,
    name: "Pepperoni Pizza",
    image: "./images/Pepperoni_Pizza.jpg",
    price: 10.49,
    description:
      "Thin crust pizza loaded with spicy pepperoni slices and melted cheese.",
    category: "Pizza",
    calories: 450,
    quantity: 1,
  },
  {
    id: 42,
    name: "Milkshake",
    image: "./images/Milkshake.jpeg",
    price: 3.75,
    calories: 300,
    description: "Creamy milkshake with vanilla ice cream.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 12,
    name: "Cheese Burger",
    image: "./images/cheese-burger.avif",
    price: 8.49,
    description:
      "Beef patty topped with melted cheddar cheese and fresh veggies.",
    category: "Burger",
    calories: 570,
    quantity: 1,
  },
  {
    id: 20,
    name: "Seafood Pasta",
    image: "./images/seafood-pasta.jpg",
    price: 12.0,
    calories: 650,
    description: "Pasta served with shrimp, calamari, and garlic sauce.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 31,
    name: "Apple Pie",
    image: "./images/Apple Pie.jpeg",
    price: 5.25,
    calories: 420,
    description: "Classic pie with sweet apple filling.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 39,
    name: "Iced Coffee",
    image: "./images/Iced-Coffee-6.jpg",
    price: 3.25,
    calories: 90,
    description: "Cold coffee served with ice cubes.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 14,
    name: "Double Beef Burger",
    image: "./images/Double Beef Burger.jpeg",
    price: 11.5,
    description: "Two juicy patties with double cheese, lettuce, and tomato.",
    category: "Burger",
    calories: 800,
    quantity: 1,
  },
  {
    id: 28,
    name: "Tiramisu",
    image: "./images/Tiramisu.jpg",
    price: 6.99,
    calories: 480,
    description: "Italian coffee-flavored dessert with mascarpone.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 41,
    name: "Mojito",
    image: "./images/Mojito.webp",
    price: 4.25,
    calories: 100,
    description: "Mint and lime refreshing summer drink.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 21,
    name: "Carbonara",
    image: "./images/Carbonara.webp",
    price: 10.75,
    calories: 700,
    description: "Egg-based sauce pasta with crispy bacon and parmesan.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 34,
    name: "Donuts",
    image: "./images/donuts.webp",
    price: 3.75,
    calories: 320,
    description: "Fluffy donuts glazed with sugar and chocolate.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 45,
    name: "Latte",
    image: "./images/Latte.jpeg",
    price: 3.2,
    calories: 120,
    description: "Smooth espresso with steamed milk.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 23,
    name: "Chicken Alfredo Pasta",
    image: "./images/Chicken-Alfredo-Pasta.jpg",
    price: 11.0,
    calories: 780,
    description: "Creamy alfredo pasta with grilled chicken breast.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 37,
    name: "Fresh Orange Juice",
    image: "./images/Fresh Orange Juice.jpeg",
    price: 2.99,
    calories: 180,
    description: "Freshly squeezed orange juice.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 24,
    name: "Mac and Cheese",
    image: "./images/mac-and-cheese.jpg",
    price: 8.25,
    calories: 650,
    description: "Baked pasta with creamy cheddar cheese sauce.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 29,
    name: "Ice Cream Sundae",
    image: "./images/Ice Cream Sundae.jpeg",
    price: 4.75,
    calories: 350,
    description: "Vanilla ice cream topped with chocolate syrup.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 4,
    name: "Veggie Pizza",
    image: "./images/vegetarian-pizza.jpg",
    price: 9.75,
    description:
      "Topped with bell peppers, mushrooms, olives, onions, and mozzarella cheese.",
    category: "Pizza",
    calories: 350,
    quantity: 1,
  },
  {
    id: 33,
    name: "Strawberry Shortcake",
    image: "./images/Strawberry Shortcake.jpg",
    price: 6.2,
    calories: 380,
    description: "Vanilla sponge cake with fresh strawberries.",
    category: "Desserts",
    quantity: 1,
  },
  {
    id: 38,
    name: "Lemonade",
    image: "./images/lemonada.jpg",
    price: 2.5,
    calories: 120,
    description: "Refreshing lemonade with mint.",
    category: "Drinks",
    quantity: 1,
  },
  {
    id: 25,
    name: "Ravioli",
    image: "./images/ravioli.jpg",
    price: 10.2,
    calories: 600,
    description: "Stuffed pasta pockets with ricotta and tomato sauce.",
    category: "Pasta",
    quantity: 1,
  },
  {
    id: 16,
    name: "Spaghetti Bolognese",
    image: "./images/Spaghetti Bolognese.jpeg",
    price: 9.99,
    calories: 600,
    description: "Classic Italian pasta with rich meat sauce and parmesan.",
    category: "Pasta",
    quantity: 1,
  },
];
