export const data = [
  {
    id: 1,
    name: "Margherita Pizza",
    image: "../images/meal-1.jpg",
    price: 8.99,
    description:
      "Classic pizza topped with tomato sauce, mozzarella cheese, and fresh basil.",
    category: "Pizza",
    calories: 300,
  },
  {
    id: 2,
    name: "Pepperoni Pizza",
    image: "../images/meal-2.jpg",
    price: 10.49,
    description:
      "Thin crust pizza loaded with spicy pepperoni slices and melted cheese.",
    category: "Pizza",
    calories: 450,
  },
  {
    id: 3,
    name: "BBQ Chicken Pizza",
    image: "../images/meal-3.jpg",
    price: 11.25,
    description:
      "Grilled chicken with smoky BBQ sauce, onions, and mozzarella cheese.",
    category: "Pizza",
    calories: 500,
  },
  {
    id: 4,
    name: "Veggie Pizza",
    image: "../images/meal-4.jpg",
    price: 9.75,
    description:
      "Topped with bell peppers, mushrooms, olives, onions, and mozzarella cheese.",
    category: "Pizza",
    calories: 350,
  },
  {
    id: 5,
    name: "Four Cheese Pizza",
    image: "../images/meal-5.jpg",
    price: 12.0,
    description:
      "Delicious blend of mozzarella, cheddar, parmesan, and gorgonzola cheese.",
    category: "Pizza",
    calories: 600,
  },

  // 🍔 Burgers
  {
    id: 11,
    name: "Classic Beef Burger",
    image: "../images/meal-6.jpg",
    price: 7.99,
    description: "Juicy beef patty with lettuce, tomato, onions, and cheese.",
    category: "Burger",
    calories: 520,
  },
  {
    id: 12,
    name: "Cheese Burger",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    price: 8.49,
    description:
      "Beef patty topped with melted cheddar cheese and fresh veggies.",
    category: "Burger",
    calories: 570,
  },
  {
    id: 13,
    name: "BBQ Bacon Burger",
    image: "https://images.unsplash.com/photo-1550317138-10000687a72b",
    price: 9.99,
    description: "Grilled beef, crispy bacon, smoky BBQ sauce, and cheese.",
    category: "Burger",
    calories: 650,
  },
  {
    id: 14,
    name: "Double Beef Burger",
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
    price: 11.5,
    description: "Two juicy patties with double cheese, lettuce, and tomato.",
    category: "Burger",
    calories: 800,
  },
  {
    id: 15,
    name: "Chicken Burger",
    image: "../images/meal-1.jpg",
    price: 7.25,
    description: "Crispy fried chicken breast with mayo and lettuce.",
    category: "Burger",
    calories: 480,
  },
  // 🍝 Pasta
  {
    id: 16,
    name: "Spaghetti Bolognese",
    image: "https://images.unsplash.com/photo-1603079849999-f7e9e9e1a8d3",
    price: 9.99,
    calories: 600,
    description: "Classic Italian pasta with rich meat sauce and parmesan.",
    category: "Pasta",
  },
  {
    id: 17,
    name: "Fettuccine Alfredo",
    image: "https://images.unsplash.com/photo-1606851094296-028b94aaf90e",
    price: 10.49,
    calories: 750,
    description: "Creamy white sauce pasta with parmesan and butter.",
    category: "Pasta",
  },
  {
    id: 18,
    name: "Penne Arrabbiata",
    image: "https://images.unsplash.com/photo-1585238342028-4f76bce3f2c8",
    price: 8.99,
    calories: 500,
    description: "Spicy tomato-based pasta with chili and garlic.",
    category: "Pasta",
  },
  {
    id: 19,
    name: "Lasagna",
    image: "https://images.unsplash.com/photo-1601924582971-3ccde3b2c4c2",
    price: 11.25,
    calories: 800,
    description: "Layers of pasta with beef, cheese, and tomato sauce.",
    category: "Pasta",
  },
  {
    id: 20,
    name: "Seafood Pasta",
    image: "https://images.unsplash.com/photo-1617196037086-5f4a4d3e4d58",
    price: 12.0,
    calories: 650,
    description: "Pasta served with shrimp, calamari, and garlic sauce.",
    category: "Pasta",
  },
  {
    id: 21,
    name: "Carbonara",
    image: "https://images.unsplash.com/photo-1625941529500-bf3b1c3a1811",
    price: 10.75,
    calories: 700,
    description: "Egg-based sauce pasta with crispy bacon and parmesan.",
    category: "Pasta",
  },
  {
    id: 22,
    name: "Pesto Pasta",
    image: "https://images.unsplash.com/photo-1605478039183-1b3c2d0b7c9a",
    price: 9.5,
    calories: 550,
    description: "Fresh basil pesto sauce with parmesan cheese.",
    category: "Pasta",
  },
  {
    id: 23,
    name: "Chicken Alfredo Pasta",
    image: "https://images.unsplash.com/photo-1606851094296-028b94aaf90e",
    price: 11.0,
    calories: 780,
    description: "Creamy alfredo pasta with grilled chicken breast.",
    category: "Pasta",
  },
  {
    id: 24,
    name: "Mac and Cheese",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    price: 8.25,
    calories: 650,
    description: "Baked pasta with creamy cheddar cheese sauce.",
    category: "Pasta",
  },
  {
    id: 25,
    name: "Ravioli",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    price: 10.2,
    calories: 600,
    description: "Stuffed pasta pockets with ricotta and tomato sauce.",
    category: "Pasta",
  },

  // 🍰 Desserts
  {
    id: 26,
    name: "Chocolate Cake",
    image: "https://images.unsplash.com/photo-1605478039183-1b3c2d0b7c9a",
    price: 5.99,
    calories: 450,
    description: "Rich and moist chocolate layered cake.",
    category: "Desserts",
  },
  {
    id: 27,
    name: "Cheesecake",
    image: "https://images.unsplash.com/photo-1617196037086-5f4a4d3e4d58",
    price: 6.5,
    calories: 500,
    description: "Creamy cheesecake with a buttery biscuit base.",
    category: "Desserts",
  },
  {
    id: 28,
    name: "Tiramisu",
    image: "https://images.unsplash.com/photo-1601924582971-3ccde3b2c4c2",
    price: 6.99,
    calories: 480,
    description: "Italian coffee-flavored dessert with mascarpone.",
    category: "Desserts",
  },
  {
    id: 29,
    name: "Ice Cream Sundae",
    image: "https://images.unsplash.com/photo-1625941529500-bf3b1c3a1811",
    price: 4.75,
    calories: 350,
    description: "Vanilla ice cream topped with chocolate syrup.",
    category: "Desserts",
  },
  {
    id: 30,
    name: "Brownie",
    image: "https://images.unsplash.com/photo-1550317138-10000687a72b",
    price: 4.5,
    calories: 400,
    description: "Fudgy chocolate brownie topped with nuts.",
    category: "Desserts",
  },
  {
    id: 31,
    name: "Apple Pie",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    price: 5.25,
    calories: 420,
    description: "Classic pie with sweet apple filling.",
    category: "Desserts",
  },
  {
    id: 32,
    name: "Panna Cotta",
    image: "https://images.unsplash.com/photo-1606851094296-028b94aaf90e",
    price: 5.99,
    calories: 300,
    description: "Creamy Italian dessert topped with berries.",
    category: "Desserts",
  },
  {
    id: 33,
    name: "Strawberry Shortcake",
    image: "https://images.unsplash.com/photo-1585238342028-4f76bce3f2c8",
    price: 6.2,
    calories: 380,
    description: "Vanilla sponge cake with fresh strawberries.",
    category: "Desserts",
  },
  {
    id: 34,
    name: "Donuts",
    image: "https://images.unsplash.com/photo-1605478039183-1b3c2d0b7c9a",
    price: 3.75,
    calories: 320,
    description: "Fluffy donuts glazed with sugar and chocolate.",
    category: "Desserts",
  },
  {
    id: 35,
    name: "Cupcakes",
    image: "https://images.unsplash.com/photo-1603079849999-f7e9e9e1a8d3",
    price: 3.5,
    calories: 280,
    description: "Mini cakes topped with colorful frosting.",
    category: "Desserts",
  },

  // 🥤 Drinks
  {
    id: 36,
    name: "Coca Cola",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349",
    price: 1.99,
    calories: 150,
    description: "Chilled soft drink served with ice.",
    category: "Drinks",
  },
  {
    id: 37,
    name: "Fresh Orange Juice",
    image: "https://images.unsplash.com/photo-1606851094296-028b94aaf90e",
    price: 2.99,
    calories: 180,
    description: "Freshly squeezed orange juice.",
    category: "Drinks",
  },
  {
    id: 38,
    name: "Lemonade",
    image: "https://images.unsplash.com/photo-1585238342028-4f76bce3f2c8",
    price: 2.5,
    calories: 120,
    description: "Refreshing lemonade with mint.",
    category: "Drinks",
  },
  {
    id: 39,
    name: "Iced Coffee",
    image: "https://images.unsplash.com/photo-1617196037086-5f4a4d3e4d58",
    price: 3.25,
    calories: 90,
    description: "Cold coffee served with ice cubes.",
    category: "Drinks",
  },
  {
    id: 40,
    name: "Hot Chocolate",
    image: "https://images.unsplash.com/photo-1601924582971-3ccde3b2c4c2",
    price: 3.5,
    calories: 210,
    description: "Warm chocolate drink topped with cream.",
    category: "Drinks",
  },
  {
    id: 41,
    name: "Mojito",
    image: "https://images.unsplash.com/photo-1625941529500-bf3b1c3a1811",
    price: 4.25,
    calories: 100,
    description: "Mint and lime refreshing summer drink.",
    category: "Drinks",
  },
  {
    id: 42,
    name: "Milkshake",
    image: "https://images.unsplash.com/photo-1550317138-10000687a72b",
    price: 3.75,
    calories: 300,
    description: "Creamy milkshake with vanilla ice cream.",
    category: "Drinks",
  },
  {
    id: 43,
    name: "Green Tea",
    image: "https://images.unsplash.com/photo-1605478039183-1b3c2d0b7c9a",
    price: 2.2,
    calories: 20,
    description: "Healthy antioxidant-rich green tea.",
    category: "Drinks",
  },
  {
    id: 44,
    name: "Espresso",
    image: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
    price: 2.5,
    calories: 15,
    description: "Strong and rich Italian coffee shot.",
    category: "Drinks",
  },
  {
    id: 45,
    name: "Latte",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
    price: 3.2,
    calories: 120,
    description: "Smooth espresso with steamed milk.",
    category: "Drinks",
  },
];
